#!/bin/bash
#===============================================================================
#
#          FILE:  radius.sh
# 
#         USAGE:  ./radius.sh 
# 
#   DESCRIPTION:  
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Kazuma Yoshiyuki (), mohamed.ladghem@kinkazma.ga
#       COMPANY:  KINKAZMA.GA
#       VERSION:  1.0
#       CREATED:  25/06/2018 20:51:03 CEST
#      REVISION:  ---
#===============================================================================

NAME="RADIUS" 
DEPENDENCIES="freeradius py-virtualenv python"

APP_DEPENDENCIES=${APP_DEPENDENCIES}"${DEPENDENCIES}"
APP_NAME=${APP_NAME}"${NAME}"  
DOMAIN="hakase.lab"

function PHASE2(){
	

}

